### ISSUE TITLE
Can't run the project

### ISSUE THREAD

**Issue by miuo** [Nethereum/Nethereum-Explorer-Wallet-Template-Blazor#11]

**Comment by anegg0** [comment]
Hi @miuo, thank you for reporting the error you're encountering. Just for confirmation, the issue occurs on the post named "Signing: Sign a message and recover the signing address", correct?
If so, could you please copy paste the returned error?

**Comment by juanfranblanco** [comment]
Closing this.. as is pretty old now and should be fixed.
