### ISSUE TITLE
Migrate to Maui Blazor and .net 6 

### ISSUE THREAD

**Issue by juanfranblanco** [Nethereum/Nethereum-Explorer-Wallet-Template-Blazor#15]
Hybrid apps were part of the preview, now is included in Maui Blazor, this needs a migration.

**Comment by migueBarrera** [comment]
Hi, I am working on a version of NethereumExplorer with .net maui. I need to do some more work but I already have a preview version. Soon I make a pull request.
https://github.com/migueBarrera/Nethereum-Explorer-Wallet-Template-Blazor

![image](https://user-images.githubusercontent.com/21368617/140906678-dbd4d4bf-2577-46a0-b934-1cf57f2bea51.png)
![image](https://user-images.githubusercontent.com/21368617/140906737-75bfa02f-e066-4343-a085-22d6e0528678.png)

**Comment by juanfranblanco** [comment]
Awesome @migueBarrera. I am actually doing the same. But awesome idea to just add the Maui project to the existing ones.

**Comment by juanfranblanco** [comment]
Feel free to make the pull now ;)

**Comment by juanfranblanco** [comment]
> Awesome @migueBarrera. I am actually doing the same. But awesome idea to just add the Maui project to the existing ones.

I would have hoped that a new template will be included on the new release that will allow you to have server and wasm platforms too, so no need to have a separate project.. but truly is much easier this way.

**Comment by juanfranblanco** [comment]
@migueBarrera Actually do you mind making the pull now, so i can merge with my stuff (as it is very similar and i would like to keep your contribution).. Ill check in the updates to the other projects.

**Comment by juanfranblanco** [comment]
@migueBarrera added my updates in master, including the upgrade of projects to latest. I have not added wwwroot and other bits and bobs that can come from your pull ;). I was thinking of linking them to the old hybrid explorer.. but that will add noise.

**Comment by juanfranblanco** [comment]
![explorerIssueWindowsMauis](https://user-images.githubusercontent.com/562371/140939737-499ebf71-ef72-4d87-8d5a-47e8c9af7a15.gif)
@migueBarrera are you having issues with windows like the above or is it just my machine

**Comment by migueBarrera** [comment]
Thank you for merge my pull request.

 I think we shouldn't have styles in the Maui project, it should use the same styles that the web uses. 


For me, windows looks like this: 
![image](https://user-images.githubusercontent.com/21368617/140994919-075d1bd3-f70b-4d49-9e30-359cbe11c77a.png)

**Comment by juanfranblanco** [comment]
I have fixed it with the latest commit.

![image](https://user-images.githubusercontent.com/562371/140995385-b8678742-a3c5-4766-a221-94506baa437c.png)

**Comment by juanfranblanco** [comment]
Although the dropdown issue remains, I think it is an issue with maui, it did not happen with the old hybrid apps.

**Comment by migueBarrera** [comment]
Ohhh great, I pull your changes and looks great. 

About the dialogue issue, yes, I think it is a WinUi issue. Xamarin used to use UWP and maui uses WinUi.

**Comment by migueBarrera** [comment]
On Android i have an issue and i don't know why.
![image](https://user-images.githubusercontent.com/21368617/140996075-0d743877-dd78-4610-a13d-34a2d9719156.png)

**Comment by juanfranblanco** [comment]
> About the dialogue issue, yes, I think it is a WinUi issue. Xamarin used to use UWP and maui uses WinUi.

Yes, hopefully it gets fixed soon, also the components having to add a reference to all the os targets is truly a pain. But I guess this is why still in preview and nearly released. Also css is not yet fixed to use the inner styles.

Re explorer should work, still a demo so not error handling in many areas.

I still wish they would have created a template included core and server.. , i guess in the near future..

**Comment by juanfranblanco** [comment]
I am closing this now!! Thanks for your help and parallel work :) it has been very nice. It is going to be very interesting in the future with all these blazor apps running everywhere!!
